#!/bin/bash
srce="${BASH_SOURCE[0]}"
while [ -h "$srce" ] ; do srce="$(readlink "$srce")"; done
wdir="$( cd -P "$( dirname "$srce" )" && pwd )"

function gogos {
tfile="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1".tga"
afile="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1".tga"
dfile="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1".tga"

tfile2="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1".tga"
afile2="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1".tga"
dfile2="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1".tga"

tfile3="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1".tga"
afile3="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1".tga"
dfile3="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1".tga"

rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1"_american_globalism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1"_american_isolationism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1"_american_wilsonianism.tga"

rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1"_american_globalism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1"_american_isolationism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1"_american_wilsonianism.tga"

rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1"_american_globalism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1"_american_isolationism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1"_american_wilsonianism.tga"

ln "$tfile" "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1"_american_globalism.tga"
ln "$afile" "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1"_american_isolationism.tga"
ln "$dfile" "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1"_american_wilsonianism.tga"


ln "$tfile2" "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1"_american_globalism.tga"
ln "$afile2" "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1"_american_isolationism.tga"
ln "$dfile2" "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1"_american_wilsonianism.tga"

ln "$tfile3" "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1"_american_globalism.tga"
ln "$afile3" "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1"_american_isolationism.tga"
ln "$dfile3" "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1"_american_wilsonianism.tga"



}
function gogo {
tfile="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/UTX.tga"
afile="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/UAL.tga"
dfile="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/USA.tga"

tfile2="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/UTX.tga"
afile2="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/UAL.tga"
dfile2="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/USA.tga"

tfile3="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/UTX.tga"
afile3="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/UAL.tga"
dfile3="/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/USA.tga"

rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1"_american_globalism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1"_american_globalism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/"$1"_american_wilsonianism.tga"

rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1"_american_globalism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1"_american_globalism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/medium/"$1"_american_wilsonianism.tga"

rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1"_american_globalism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1"_american_globalism.tga"
rm "/home/andy/Desktop/HOVMODDING/LocalUser/mod/UAS/gfx/flags/small/"$1"_american_wilsonianism.tga"

ln "$tfile" "$1"_american_globalism.tga
ln "$afile" "$1"_american_isolationism.tga
ln "$dfile" "$1"_american_wilsonianism.tga


ln "$tfile2" medium/"$1"_american_globalism.tga
ln "$afile2" medium/"$1"_american_isolationism.tga
ln "$dfile2" medium/"$1"_american_wilsonianism.tga

ln "$tfile3" small/"$1"_american_globalism.tga
ln "$afile3" small/"$1"_american_isolationism.tga
ln "$dfile3" small/"$1"_american_wilsonianism.tga



}
gogos "USA"
gogos "UMI"
gogos "UIL"
gogos "UNY"
gogos "UAL"
gogos "UCA"
gogos "UTX"
gogos "UIN"
gogos "UCI"
gogos "UDK"
gogos "UMN"
gogos "UEN"
gogos "UKY"
gogos "UTN"
gogos "UMS"
gogos "UFL"
gogos "UGO"
gogos "UVA"
gogos "UNE"
gogos "UME"
gogos "UAR"
gogos "ULA"
gogos "UWI"
gogos "UOK"
gogos "UIA"
gogos "UKA"
gogos "UOH"
gogos "UPE"
gogos "UML"
gogos "UNJ"
gogos "UWA"
gogos "UID"
gogos "UAZ"
gogos "UUT"
gogos "UNV"
gogos "UOR"
gogos "UMO"
gogos "UCO"
gogos "UMX"
gogos "UWY"
gogos "UHW"
gogos "UAK"
gogo "KOS"
gogo "GER"
gogo "ENG"
gogo "SOV"
gogo "SWE"
gogo "FRA"
gogo "LUX"
gogo "BEL"
gogo "HOL"
gogo "CZE"
gogo "POL"
gogo "AUS"
gogo "LIT"
gogo "EST"
gogo "LAT"
gogo "SPR"
gogo "ITA"
gogo "ROM"
gogo "YUG"
gogo "SER"
gogo "SWI"
gogo "TUR"
gogo "GRE"
gogo "ALB"
gogo "NOR"
gogo "DEN"
gogo "BUL"
gogo "POR"
gogo "FIN"
gogo "IRE"
gogo "HUN"
gogo "AFG"
gogo "ARG"
gogo "AST"
gogo "BHU"
gogo "BOL"
gogo "BRA"
gogo "CAN"
gogo "CHI"
gogo "CHL"
gogo "COL"
gogo "COS"
gogo "ECU"
gogo "ELS"
gogo "ETH"
gogo "GUA"
gogo "HON"
gogo "IRQ"
gogo "JAP"
gogo "KOR"
gogo "LIB"
gogo "MEX"
gogo "MEN"
gogo "NEP"
gogo "NIC"
gogo "NZL"
gogo "PAN"
gogo "PER"
gogo "PHI"
gogo "PRU"
gogo "SAF"
gogo "SAU"
gogo "SIA"
gogo "SIK"
gogo "TIB"
gogo "URG"
gogo "VEN"
gogo "YUN"
gogo "MON"
gogo "TAN"
gogo "PAR"
gogo "CUB"
gogo "DOM"
gogo "HAI"
gogo "YEM"
gogo "OMA"
gogo "SLO"
gogo "RAJ"
gogo "CRO"
gogo "GXC"
gogo "PRC"
gogo "SHX"
gogo "XSM"
gogo "ICE"
gogo "LEB"
gogo "JOR"
gogo "SYR"
gogo "EGY"
gogo "LBA"
gogo "WGR"
gogo "DDR"
gogo "PAL"
gogo "ISR"
gogo "VIN"
gogo "CAM"
gogo "MAL"
gogo "INS"
gogo "LAO"
gogo "MNT"
gogo "UKR"
gogo "GEO"
gogo "KAZ"
gogo "AZR"
gogo "ARM"
gogo "BLR"
gogo "ANG"
gogo "MZB"
gogo "ZIM"
gogo "COG"
gogo "KEN"
gogo "PAK"
gogo "BOT"
gogo "MAN"
gogo "BAH"
gogo "BAN"
gogo "BLZ"
gogo "BRM"
gogo "CRC"
gogo "GDL"
gogo "GYA"
gogo "JAM"
gogo "KYR"
gogo "MAD"
gogo "MOL"
gogo "PNG"
gogo "PUE"
gogo "QAT"
gogo "SCO"
gogo "SRL"
gogo "SUR"
gogo "TAJ"
gogo "TRI"
gogo "TMS"
gogo "UAE"
gogo "UZB"
gogo "KUW"
gogo "CYP"
gogo "MLT"
gogo "ALG"
gogo "MOR"
gogo "TUN"
gogo "SUD"
gogo "ERI"
gogo "DJI"
gogo "SOM"
gogo "UGA"
gogo "RWA"
gogo "BRD"
gogo "TZN"
gogo "ZAM"
gogo "MLW"
gogo "GAB"
gogo "RCG"
gogo "EQG"
gogo "CMR"
gogo "CAR"
gogo "CHA"
gogo "NGA"
gogo "DAH"
gogo "TOG"
gogo "GHA"
gogo "IVO"
gogo "VOL"
gogo "MLI"
gogo "SIE"
gogo "GNA"
gogo "GNB"
gogo "SEN"
gogo "GAM"
gogo "WLS"
gogo "NGR"
gogo "CSA"
gogo "USB"
gogo "MRT"
gogo "NMB"
gogo "WES"
gogo "BAS"
gogo "CAY"
gogo "MLD"
gogo "FIJ"
gogo "FSM"
gogo "TAH"
gogo "GUM"
gogo "SOL"
gogo "SAM"
gogo "HAW"
gogo "SLV"
gogo "BOS"
gogo "HRZ"
gogo "MAC"
gogo "NIR"
gogo "BAY"
gogo "MEK"
gogo "PRE"
gogo "SAX"
gogo "HAN"
gogo "WUR"
gogo "SHL"
gogo "CAT"
gogo "NAV"
gogo "GLC"
gogo "ADU"
gogo "BRI"
gogo "OCC"
gogo "COR"
gogo "KUR"
gogo "TRA"